### ISSUE TITLE
Case Classes that differ for Aggregation Pipelines

### ISSUE THREAD

**Issue by Executioner1939** [zeal18/zio-mongodb#72]
Hi,

I would like to use a different class that the top-level type supplied to the `MongoCollection[A]` when working with aggregation pipelines.

I am trying to create a PR for this but don't quite understand how the `Codec[A]` would be used, for example:

```scala
    override def aggregate[B](pipeline: Seq[Aggregation])(implicit codec: Codec[B]): AggregateQuery[B] =
      AggregateQuery(wrapped.aggregate[B](pipeline.asJava, classOf[B]))
```

Given the type is passed to the underlying Java MongoCollection, I don't quite understand the flow :-). Not sure if you could give some pointers :-).

**Comment by zeal18** [comment]
Hi Richard!
It's a tricky one because the underlying Java driver resolves codecs in the runtime using the codec registry, but we want to have a compile-time check that we've registered a codec. That's why the codec registration happens only during a collection instantiation. I have an idea how to make it possible to provide codecs to a collection methods like aggregation, but it requires some time for investigation and implementation. Currently there is a workaround: you can call `yourCollection.withDocumentClass[B]` which instantiates another collection with a different codec registered for the same MongoDB collection. At the end you will have two collection instances, the first with codec `A` for find/insert/update queries and the second one with codec `B` for the aggregate queries.

**Comment by Executioner1939** [comment]
Hi @zeal18 thanks for responding, I thought it might be tricky as I could see the `Codec`'s were only used when constructing the `MongoCollection[A]`, for now I will use your workaround, thanks :-)
